Repository AY2425S1-CS2103T-W14-2/tp, pull requests merged in 2024-11, with the labels that each got.

#160 Add tag values to CSV export
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.High, alpha-bug

#181 Display Persons with null tag value when using advfilter
  src/main/java/seedu/address/logic/commands/AdvFilterCommand.java
Labels: priority.High, priority.Medium, alpha-bug, documentation

#215 Allow decimals for tag values
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Low, alpha-bug

#214 Add CSV and TXT export GUI buttons
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#213 Flag invalid tag arguments
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.High, alpha-bug

#222 Update UG: `export`
  docs/UserGuide.md
  docs/images/exportGUIEg.png
Labels: priority.High, documentation

#223 Update UG: Add/Refine minor details.
  docs/UserGuide.md
Labels: priority.Medium, documentation

#227 Update User Guide for Sort Command
  docs/UserGuide.md
Labels: priority.High, alpha-bug, documentation

#234 Refactor `sort` command
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: priority.Medium

#236 Fix problems with the "Known Issues" section in the UG
  docs/UserGuide.md
Labels: documentation

#287 Update `export`'s documentation across the product
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: severity.Low, documentation

#291 Patch issue with `export` throwing an error if `bae_addressbook.json` does not exist
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High

#293 Amend AdvFilter behaviour
  src/main/java/seedu/address/logic/commands/AdvFilterCommand.java
Labels: priority.Medium, severity.Medium

#294 Fix sort behvaiour to be case-insensitive
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: priority.Medium, severity.Medium

#219 Fix whitespace trimming bug in ExportCommand
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#306 Reformat tags in TXT exports
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Bug, severity.VeryLow

#310 Update DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
Labels: documentation
