Repository AY2425S1-CS2103T-W14-2/tp, pull requests merged in 2024-10, with the labels that each got.

#36 Update user stories, use cases, non-functional requirements, glossary…
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#51 Add partial CSV export functionality
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#60 Add CSV export functionality
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: priority.High

#61 Add Sort command functionality
  .gitignore
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#64 Update config for shadowJar in build.gradle & Reupload docs/images/MVPSort.png
  build.gradle
  docs/images/MVPSort.PNG
  docs/images/MVPSort.png
Labels: severity.Low

#85 Fix regression issues related to `export`
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Bug, priority.High, severity.High

#95 Create export diagram
  docs/diagrams/ExportCommand.puml
Labels: priority.Medium

#87 Patch `tags` format in CSV export
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Bug, priority.High, priority.Medium, severity.Medium

#101 Add PlantUML diagram file for SortCommand (WIP)
  docs/diagrams/SortCommand.puml
Labels: priority.High

#144 Update DG design and requirements
  docs/DeveloperGuide.md
Labels: priority.Medium

#151 Implement Sort Command feature
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#150 AdvFilterCommandParser.java: Check for valid operators when parsing
  src/main/java/seedu/address/logic/commands/AdvFilterCommand.java
  src/main/java/seedu/address/logic/parser/AdvFilterCommandParser.java
  src/test/java/seedu/address/logic/commands/AdvFilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AdvFilterCommandParserTest.java
Labels: priority.High, alpha-bug
